### ISSUE TITLE
给出参考配置文件

### ISSUE THREAD

**Issue by liang2kl** [robertying/learnX-companion#3]
是否可以在 README 或者在仓库中添加参考配置文件，从而可以直接用于 cli？（下载一个 GUI 再导出配置文件显得有点多余）

理论上，只有这些设置不太平凡：

- `lastSyncTime`：使用 `date` 等命令行工具生成当前时间即可，如 `date +%Y-%m-%dT%H:%M:%S%Z`
- `excludedCourses`：感觉一般不需要（毕竟官方的推送也不支持）；如果需要的话，可以考虑在 learnX 中展示课程的 id？

**Comment by robertying** [comment]
Closed by [b1d3f5b](https://github.com/robertying/learnX-companion/commit/b1d3f5b523a5e95de1a658edb2302785c0995802)
