### ISSUE TITLE
学校更新网络学堂后失效，无法推送通知，请求修复

### ISSUE THREAD

**Issue by erbanku** [robertying/learnX-companion#4]
如题

**Comment by robertying** [comment]
App 请确保获取了最新的热更新版本。马上也会有新的 App Store 版本。
learnX Companion 的话近几天会更新来支持。

**Comment by robertying** [comment]
请验证最新版：https://github.com/robertying/learnX-companion/releases/tag/v2.4.0

**Comment by erbanku** [comment]
> 请验证最新版：[`v2.4.0` (release)](https://github.com/robertying/learnX-companion/releases/tag/v2.4.0)

可以了😊
